.PHONY: clean All

All:
	@echo "----------Building project:[ DeclaredClassAndObjects - Debug ]----------"
	@cd "DeclaredClassAndObjects" && "$(MAKE)" -f  "DeclaredClassAndObjects.mk"
clean:
	@echo "----------Cleaning project:[ DeclaredClassAndObjects - Debug ]----------"
	@cd "DeclaredClassAndObjects" && "$(MAKE)" -f  "DeclaredClassAndObjects.mk" clean
