.PHONY: clean All

All:
	@echo "----------Building project:[ Random - Debug ]----------"
	@cd "Rand" && "$(MAKE)" -f  "Random.mk"
clean:
	@echo "----------Cleaning project:[ Random - Debug ]----------"
	@cd "Rand" && "$(MAKE)" -f  "Random.mk" clean
