.PHONY: clean All

All:
	@echo "----------Building project:[ MPGFunctionMultipleExceptions - Debug ]----------"
	@cd "MPGFunctionMultipleExceptionsSection18" && "$(MAKE)" -f  "MPGFunctionMultipleExceptions.mk"
clean:
	@echo "----------Cleaning project:[ MPGFunctionMultipleExceptions - Debug ]----------"
	@cd "MPGFunctionMultipleExceptionsSection18" && "$(MAKE)" -f  "MPGFunctionMultipleExceptions.mk" clean
