.PHONY: clean All

All:
	@echo "----------Building project:[ PaassingPointers3 - Debug ]----------"
	@cd "PaassingPointers3" && "$(MAKE)" -f  "PaassingPointers3.mk"
clean:
	@echo "----------Cleaning project:[ PaassingPointers3 - Debug ]----------"
	@cd "PaassingPointers3" && "$(MAKE)" -f  "PaassingPointers3.mk" clean
