.PHONY: clean All

All:
	@echo "----------Building project:[ Dereference - Debug ]----------"
	@cd "Dereferemce" && "$(MAKE)" -f  "Dereference.mk"
clean:
	@echo "----------Cleaning project:[ Dereference - Debug ]----------"
	@cd "Dereferemce" && "$(MAKE)" -f  "Dereference.mk" clean
