.PHONY: clean All

All:
	@echo "----------Building project:[ StatelessLambdas - Debug ]----------"
	@cd "StatelessLambdas" && "$(MAKE)" -f  "StatelessLambdas.mk"
clean:
	@echo "----------Cleaning project:[ StatelessLambdas - Debug ]----------"
	@cd "StatelessLambdas" && "$(MAKE)" -f  "StatelessLambdas.mk" clean
